language: node_js
node_js:
  - "8.11.1"
cache:
  directories:
    - ".meteor"
    - ".babel-cache"
script: TEST_PACKAGES_EXCLUDE="less" phantom=false ./packages/test-in-console/run.sh
sudo: false
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
